image: node:alpine

cache:
  paths:
    - node_modules

stages:
  - deploy

pages:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=megamindwalletui --api-key=$HEROKU_API_KEY
    - yarn install
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish
